### PR TITLE
Feature/bathymetry

### PR DESCRIPTION
**Pull request by hawbecker**
Files and directions added for running with the depth-dependent sea surface roughness calculation.

### CODE REVIEW

**Comment by ewquon** [comment]
Will test this over the next week.

**Comment by hawbecker** [comment]
@ewquon - the setup for using ERA5 has been finalized with this. Let me know if there's anything else I need to do / if you need help testing.

**Comment by hawbecker** [comment]
@ewquon just wanted to ping you on this - looks like some people are ready to start running

**Comment by hawbecker** [comment]
We can update later if needed - this is a good starting point for everybody.

**Pull request merged**
